### ISSUE TITLE
Log in with OAuth

### ISSUE THREAD

**Issue by rjmunro** [web-pal/chronos-timetracker#76]
## Expected Behavior

When setting up the desktop app, I should be presented with a browser window and asked to log in. The app should then receive an OAuth token to work.

## Actual Behavior

I am asked to enter my password directly into the app.

This doesn't work as I don't have a Jira password. I log in to Jira with single sign on from my company Google account. It's also less secure because my password might be stored somewhere in the app, rather than just a token that I can cancel in Jira (on the https://[whatever].atlassian.net/plugins/servlet/oauth/users/access-tokens screen)

## Specifications

  - Chronos-timetracker version: 2.5.9 
  - OS: Mac OS

**Comment by ChangJoo-Park** [comment]
👍

**Comment by kevingelion** [comment]
My team also uses SSO through Okta so this would be super helpful!

**Comment by jloh** [comment]
oAuth would be better! Our security policy prohibits me from putting my standard pass into this app sadly.

**Comment by tracstarr** [comment]
was this re-enabled? We also use google managed accounts so not able to use this currently.

**Comment by spacebromx** [comment]
Same @tracstarr mentioned. My company is using Google Accounts for login.

**Comment by fobid** [comment]
I couldn't to use it neither. I had same reason with above comments.

**Comment by pospile** [comment]
+1 Please enable Google login support!

**Comment by VladimirPal** [comment]
@pospile @fobid @spacebromx @tracstarr @jloh @Elderry @kevingelion @ChangJoo-Park @rjmunro 
Hi! Could you check 2.8.1, please? All types of authorization should work now!

**Comment by pospile** [comment]
@VladimirPal yes, its working! Thanks.

**Comment by Yozhig** [comment]
Still does not work. Version 5.0.1.

**Comment by gsprdev** [comment]
@rjmunro described the issue well, and it is still an issue in the latest version (I have never seen an earlier version).

Even though multiple login types appear supported, all of it is exposed through an embedded web view rather than by calling out to the standard web browser. The fact remains that to log in my only choice would be to type my company-wide SSO credentials directly into this app, which is a non-starter.

I was excited to try your tool, it looks like you put a lot of love into it, but sadly my evaluation ended before I even logged in.
